// Re-export all deck functions from the Supabase implementation
export {
  listDecks,
  createDeck,
  renameDeck,
  deleteDeck,
  getDeckAndAllChildren,
  getDeckPath,
  listDecksWithPaths,
  listCards,
  listCardsForDeckTree,
  listAllCards,
  setCardDueDate,
  forgetCard,
  setCardMarked,
  createCard,
  deleteCard,
  updateCard,
  suspendCard,
  unsuspendCard,
  moveCardsToDeck,
  getDueCards,
  getDueCount,
  getTotalCardCount,
  getDeckCardCounts,
  getAllDeckCounts,
  getAnkiCountsForDecks,
  invalidateDeckCaches,
  invalidateCardCaches,
  reviewCard,
  getCardsStudiedToday,
  getCurrentStreak,
  getTotalReviews,
  getSettings,
  updateSettings,
  // Scheduler functions
  previewIntervals,
  formatInterval,
  formatIntervalDays,
  parseSteps,
  // Types
  type Deck,
  type Card,
  type Review,
  type ImportDoc,
  type GeneratedCard,
  type IntervalPreview,
  type SchedulerSettings,
  type Settings,
  type DeckMode,
} from "@/lib/supabase-db";
